export const moviesInitialState = {
  loading: false,
  error: null,
  allMovies: [],
  heroMovie: {
    id: '580489',
    description: '',
    trailer: '',
    title: '',
    key: '',
    poster: '',
    backdrop: '',
    backdropHighRes: '',
    posterHighRes: '',
    runtime: '',
  },
  bottomSheetMovie: {
    id: '580489',
    description: '',
    trailer: '',
    title: '',
    key: '',
    poster: '',
    backdrop: '',
    backdropHighRes: '',
    posterHighRes: '',
    runtime: '',
  },
  movieDetails: {
    id: '580489',
    movieDetailsResults: {
      actors: [
        'Tom Hardy',
        'Woody Harrelson',
        'Michelle Williams',
        'Naomie Harris',
        'Reid Scott',
        'Stephen Graham',
        'Peggy Lu',
        'Sian Webber',
        'Michelle Greenidge',
      ],
      certificationDefinition:
        'Potentially harmful to children under 12 years; broadcasting is not allowed before 8:00 pm.',
      directors: ['Andy Serkis'],
      genres: ['Science Fiction', 'Action', 'Adventure'],
      releaseDate: '2021',
      writers: ['Tom Hardy'],
    },
  },
  searchMovies: [],
  searchInput: '',
};
