// ENUM FOR ACTION NAMES

export enum ActionType {
  FETCH_USER_SUCCESS = 'fetch_user_success',
  FETCH_USER_ERROR = 'fetch_user_error',
  SIGNUP_USER_SUCCESS = 'signup_user_success',
  SIGNUP_USER_ERROR = 'signup_user_error',
  SIGNOUT_USER_SUCCESS = 'signout_user_success',
  SIGNOUT_USER_ERROR = 'signout_user_error',
  SIGNIN_USER_SUCCESS = 'signin_user_success',
  SIGNIN_USER_ERROR = 'singnin_user_error',
  SEARCH_ACTIVE = 'search_active',
  SEARCH_INACTIVE = 'search_inactive',
  HIDE_MAINNAV = 'hide_mainnav',
  SHOW_MAINNAV = 'show_mainnav',
  SHOW_BOTTOMSHEET = 'show_bottomsheet',
  HIDE_BOTTOMSHEET = 'hide_bottomsheet',
  SCROLLY_ZERO_TRUE = 'scrolly_zero_true',
  SCROLLY_ZERO_FALSE = 'scrolly_zero_false',
  HIDE_DISCOVERNAV = 'hide_discovernav',
  SHOW_DISCOVERNAV = 'show_discovernav',
  CHANGE_CURRENTROUTE = 'change_currentroute',
  REQUEST_MOVIES_SUCCESS = 'request_movies_success',
  REQUEST_MOVIES_FAILURE = 'request_movies_failure',
  SINGLE_MOVIE = 'single_movie',
  ALL_MOVIES = 'all_movies',
}
